#!/bin/sh

TMP_BASE_DIR=/tmp
TMP_PROFILE_DIR="incognitus_`date | md5`"
nohup /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --no-default-browser-check --no-first-run --incognito --user-data-dir=${TMP_BASE_DIR}/${TMP_PROFILE_DIR} $1 >> /dev/null && rm -rf ${TMP_BASE_DIR}/${TMP_PROFILE_DIR} 2>&1 &